name: Lint

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1.0.0
    - uses: max/awesome-lint@v2.0.0
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - name: Install awesome_bot
      run: gem install awesome_bot
    - name: Lint
      run: awesome_bot README.md
